### ISSUE TITLE
2/8: Assignment: Solitaire Implementation Strategy

### ISSUE THREAD

**Issue by michaelcarroll** [Acucentri/issue-repo#16]

**Comment by CTATE001** [comment]
Solitaire Solver Algoritm v1
Team - Acucentri

Shuffle Cards:

Real-Time Game:
 1. Place (1..7) Card(s) on spot (1..7) of the Tableau from the Stock
 2. Remove card from the Stock and add to Talon (or discard) stack
 3. While (count<=3 or there are still moves
 4.    While there are still moves in Tableau
 5.       For(Cards Focus: Tableau)
 6.          For(Cards Target: Tableau)
 7.             if Focus.top.high.value equals (Taget.top.low.value)-1 and Focus.top.high.color!=Taget.top.low.color then,
 8.                Move Focus.top to Target.top
 9.                if Focus.bottom!=null then, Move Focus.bottom.high to Focus.top
10.             else there are no moves
11.    If Stock.size equals 0 and count<=3 then,
12.       count++
13.       Move Talon.end->start to Stock.start->end
14.    If Talon is empty and Stock is not then, move Stock.top to Talon.top 
15.       If Talon.top.value equals 0 (Ace) then, move Talon.top to Foundation
16.       For(Cards Target: Tableau)  
17.          If (Talon.top.value equals (Taget.top.low.value)-1 and Talon.top.low.color!=Target.color) or (target.top=NULL and Talon.top.value equals 12) then,
18.             Move Talon.top to Target.top and break
19.          else there are no moves
20. If there are no moves and Talon isnt empty and count>3 then, game over you lost
21. For(Cards Focus: Tableau)
22.    For(Cards Target: Foundation)
23.    If (Focus.top.low.value)-1 equals Target.high then,
24.       Move Focus.top.low to target.highand break
25. If Foundation[0..3].top.value equals 12 then, you have won
